### ISSUE TITLE
Does UO Fiddler store any information in the Windows registry?

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/UOFiddler#10]
If so, please switch to an ini or cfg file for saving info such as UO files location. Preferably this file would be saved in the directory where the UO Fiddler exe resides but given the heightened security on Windows I don't know if this is possible for those who place Fiddler on their C drive. I would be happy to test it if you create a special build but I suppose it's an easy test for you.

I don't know, maybe Fiddler stores this info in the Users area of Windows. If so I guess that is ok.

**Comment by turleypol** [comment]
No registry is not used, the options get stored in your appdata folder
