### ISSUE TITLE
bug "replace starting from"

### ISSUE THREAD

**Issue by Tolokio** [polserver/UOFiddler#101]
when u use "replace starting from" uofiddler duplicates slots..

edit. The slots's duplication seems to be only visual. if u hide and unhide empty slots it gets fixed.

 the feature "Show free slots" have another bug. There is a way u can invert show free slots option and could be related with slots duplications cos it didnt happens to me before.

Just mark "show free slots" and free slots will be shown.  Then u reload scripts and "Show free slots" will stay marked, but all free slots will be hidden. If u unmark free slots they will appear again.
If u dont have the slot's duplication mod, try to do this second bug, and check again.

note: it only happens to me at Textures tabs and landtiles tab

**Comment by AsYlum-** [comment]
I think it should work now :) Please test it and let me know https://github.com/polserver/UOFiddler/releases/tag/4.9.15

**Comment by Tolokio** [comment]
It works for me. Ty a lot. Even the "reaload files" is fixed. GJ

**Comment by AsYlum-** [comment]
Fixed.
