### ISSUE TITLE
Animdata Export To CSV and Import To CSV

### ISSUE THREAD

**Issue by DavideRei** [polserver/UOFiddler#114]
Right now adding a lot of animated items is very time consuming.
It would be very useful in Animdata tab to have a button to Export To CSV and one to Import to CSV, like in tiledata tab.

**Comment by AsYlum-** [comment]
CSV is not a good format for this as animdata entry has weird data structure it's not list of item id's as you seen them in UI. It's just list of offsets. So it translates to start + 1 , start +2 etc.

I'll take a look but right now CSV looks pretty bad as a data format for import/export.

**Comment by DavideRei** [comment]
An alternative could be to add animData compare in the Compare plugin, so you can copy an animated item from animdata 2 to animdata 1.

**Comment by demostenescz666** [comment]
We are uprading data to HS format and this is indeed issue. Everything is easy to copy into "bigger" muls, except animdata. So far only chance is to manully set our custom animated items again. So at least ability to copy one animdata to other would help.
