### ISSUE TITLE
Add the right panel back to the sound tab.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/UOFiddler#2]
At some point the right panel was removed from the sound tab in favour of a right-click context menu. I would like the right panel restored please. The context menu is fine too. See
[this image](http://hopelives.us/Images/old_style_sound_tab.png) for an example of the right pane.

**Comment by AsYlum-** [comment]
Example image for reference added to this issue to prevent accidental loss.

![old_style_sound_tab](https://user-images.githubusercontent.com/377468/87050231-48798980-c1fe-11ea-8044-ecc30ac6fcc3.png)
