### ISSUE TITLE
Animations max number

### ISSUE THREAD

**Issue by Rex-deadwall** [polserver/UOFiddler#58]
The max animations number listed in the Animations tab should be 2048. I was able to list the entries up to and even past 2048, but the actual animations don't show up.
Animationlist.xml

```
<Mob name="test (2047)" body="2047" type="2" />

<Mob name="test (2048)" body="2048" type="2" />

<Mob name="test (2049)" body="2049" type="2" />
```

Bodyconv.def
```
2047	2	-1	-1	-1 	#test

2048	2	-1	-1	-1 	#test

2049	2	-1	-1	-1 	#test
```

The highest i was able to get to work is 1696. 1697 won't show up.
Animationlist.xml

```

<Mob name="test (1696)" body="1696" type="0" />


<Mob name="test (1697)" body="1697" type="0" />
```

Bodyconv.def

```
1696	2	-1	-1	-1 	#test

1697	2	-1	-1	-1 	#test
```

Thanks!

**Comment by AsYlum-** [comment]
Well it took me a while to look into this but it's fixed in latest pre-release. Max body id is now 2048. I think that 4.9.7 will be fully available in around a week. For now you can try pre-release: https://github.com/polserver/UOFiddler/releases
