### ISSUE TITLE
After activating test plug-in, items do not export to itemdesc.cfg - 4.9.4 pre

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/UOFiddler#64]
This works in 4.9 but not 4.9.4 pre-release.

**Comment by Admin-Yukiko** [comment]
I neglected to mention that Fiddler 4.9.4 pre creates an empty itemdesc.cfg file.

**Comment by AsYlum-** [comment]
That one is actually weird but I think it's another bug that I've found some time ago. Do you have more than one installation of uo client on your system?
