### ISSUE TITLE
Animdata tab not saving changes in file

### ISSUE THREAD

**Issue by meaowR** [polserver/UOFiddler#72]
Animdata tab not saving changes in file
trying same in 4.9.2 is ok but in latest it's not work

**Comment by AsYlum-** [comment]
It's fixed in pre-release https://github.com/polserver/UOFiddler/releases/tag/4.9.6 so you can try that or wait until the pre-release will become full 4.9.6 release or just use older version for now. Probably in next few days.

**Comment by AsYlum-** [comment]
I've finished new version 4.9.6 and it's now marked as full release. This issue is fixed there.
