### ISSUE TITLE
Suggestion: Items & TileData tabs: Select in Gumps Tab right-click option

### ISSUE THREAD

**Issue by Slegnor** [polserver/UOFiddler#75]
Would it be possible for a "Select in Gumps Tab" option in the right click menu in the Items and Tiledata tabs?
It would use the Anim prop number on Items/TileData to locate the relevant Gump, using the last 3 of the decimal gump ID.
Would only need to target the "Male" gump item as the "Jump to Female" option is already available.

**Comment by AsYlum-** [comment]
Hmm from what I know it's not last 3 digits in anim it is `anim + 50000` for male and `anim + 60000` for female. There is also gump.def which UOFiddler is not parsing at the moment. 

That's what we can find in gump.def: 
> \# Note that you have to do more for wearables then weapons - specifically, you have to
> \# add female and male defaults.  That's what the second batch that starts at 60,000 is.
> \# Otherwise, when drawing a female pdoll wearable, it'll use male art.  

So in short. Yes it's possible and I will try to add it.

**Comment by AsYlum-** [comment]
It wasn't that time consuming os here it is. You can test it in pre-release version https://github.com/polserver/UOFiddler/releases/tag/4.9.7 

Context menu also tries to check if the gump is present. So for example when there is only male gump it will disable female menu item. For no gumps both are disabled.

![image](https://user-images.githubusercontent.com/377468/106960359-40ee7480-673c-11eb-96cd-9ba2cca579a0.png)

**Comment by Slegnor** [comment]
Most excellent, works great
