### ISSUE TITLE
Remember window size.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/UOFiddler#9]
Have UO Fiddler remember its window size from the last time it was open. I suppose this means it needs to save that in an ini or cfg file. Please don't use the Windows registry!

**Comment by turleypol** [comment]
If I remember correctly this is already included. I think there is somewhere a checkbox to activate it.

**Comment by AsYlum-** [comment]
There is one in About it's called "Store form state". I'm not sure if it's applied to all windows already. Probably not so still needs some improvements.

**Comment by AsYlum-** [comment]
This one looks solved so closing.
