### ISSUE TITLE
MultiEditor add new tile

### ISSUE THREAD

**Issue by andrtechno** [polserver/UOFiddler#96]
How add tile??
multieditor.xml not work

**Comment by AsYlum-** [comment]
You need to update multieditor.xml but the one located in your profile folder. C:\Users\<user_name>\AppData\Roaming\UoFiddler\plugins\multieditor.xml or %appdata%\UoFiddler\plugins\multieditor.xml 

The one that exists in UOFiddler directory is only used when first creating user profile.

**Comment by andrtechno** [comment]
@AsYlum- thx

**Comment by andrtechno** [comment]
@AsYlum- thx
