### ISSUE TITLE
Import and Export multis without changes will change MultiRegion of objects (video included)

### ISSUE THREAD

**Issue by Tibald** [polserver/UOFiddler#99]
Hello, here video of bug with export and import object in multis without any changes:

https://youtu.be/VTQF15Bh9ng

1. Open UOFiddler
2. Select Multis
3. Select - 0x9C - Sandastone Patio House
4. Export it to TXT
5. Import it back from TXT.

As result you will see that MultiRegion will be changed:
OLD:     -5, -4, 6, 5 
NEW:    -5, -5, 6, 4

**Comment by AsYlum-** [comment]
@Tibald  It should be fixed for Multi tab. You can get the latest version here: https://github.com/polserver/UOFiddler/releases/tag/4.9.13
